[package]
name = "denispionicul/stater"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
description = "A finite state machine module with a lot of features and customisability."
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1.1.0"
Signal = "sleitnick/signal@2.0.1"