[package]
name = "denispionicul/queue"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
description = "Queue class for ordered function calling."
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.1"